services:
  db:
    image: postgres:16-alpine
    container_name: postgres_server
    restart: always
    environment:
      - POSTGRES_USER=kotitas
      - POSTGRES_PASSWORD=kotitas
      - POSTGRES_DB=kotitas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
